Dominios Soporte y RMA. Permisos y doctypes.
fproldan/erpnext pull request #10
Opened 2021-10-19 14:53 UTC by fproldan

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2021-10-21 15:57 UTC, lucasvazq requested changes

2021-10-21 15:57 UTC, lucasvazq commented on erpnext/support/setup.py
> +                dict(role='System Manager')
Fran, estos roles son diferentes a los listados en:
- `erpnext/support/report/support_hour_distribution/support_hour_distribution.json`
- `erpnext/domains/support.py`

Te lo menciono porque tal vez está bien que sea así pero yo no sé.

2021-10-22 10:56 UTC, fproldan commented on erpnext/support/setup.py
> +                dict(role='System Manager')
Esta ok

2021-10-22 11:11 UTC, lucasvazq approved these changes

2021-10-26 13:06 UTC, lucasvazq approved these changes

2021-10-26 13:24 UTC, merged