feat: pagos360
fproldan/erpnext pull request #7
Opened 2021-08-23 14:30 UTC by fproldan

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2021-10-07 18:13 UTC, lucasvazq requested changes

2021-10-07 18:13 UTC, lucasvazq commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
> +def make_purchase_receipt(source_name, target_doc=None, caca=None):
Quitar este parámetro

2021-10-07 18:13 UTC, lucasvazq commented on erpnext/accounts/doctype/payment_request/payment_request.py
> +			"email_to": args.recipient_id,  # or ref_doc.owner,
Faltó descomentar?

2021-10-07 18:13 UTC, lucasvazq commented on erpnext/accounts/doctype/subscription/subscription.js
> +						console.log(r.message)
Se puede quitar este log

2021-10-12 11:30 UTC, fproldan commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
> +def make_purchase_receipt(source_name, target_doc=None, caca=None):
Fue un chanchullo para solucionar un error que daba cuando fede tenia que hacer una demo, lo saco porque los hindu lo corrijieron bien, tengo otra tarjeta para bajar esos cambios

2021-10-12 11:31 UTC, fproldan commented on erpnext/accounts/doctype/payment_request/payment_request.py
> +			"email_to": args.recipient_id,  # or ref_doc.owner,
Ahi lo comentado es el codigo original de erpnext, lo otro una modificación que hicimos, borro el comentario.

2021-10-12 12:53 UTC, lucasvazq approved these changes

2021-11-03 13:36 UTC, merged